export const SET_ACTIVE_WINDOW = 'SET_ACTIVE_WINDOW'
export const REFRESH_INVOICE_LIST = 'REFRESH_INVOICE_LIST'
export const REFRESH_WARES_INVOICE_LIST = 'REFRESH_WARES_INVOICE_LIST'
export const REFRESH_INVENT_LIST = 'REFRESH_INVENT_LIST'
export const REFRESH_WARES_INVENT_LIST = 'REFRESH_WARES_INVENT_LIST'
export const REFRESH_EDIT_INVOICE_FORM = 'REFRESH_EDIT_INVOICE_FORM'
export const REFRESH_TRANSFER_INVOICE_LIST = 'REFRESH_TRANSFER_INVOICE_LIST'
export const REFRESH_WARES_TRANSFER_INVOICE_LIST = 'REFRESH_WARES_TRANSFER_INVOICE_LIST'
export const SET_ACTIVE_TRANSFER_INVOICE = 'SET_ACTIVE_TRANSFER_INVOICE'
export const SET_ACTIVE_INVOICE = 'SET_ACTIVE_INVOICE'
export const SET_ACTIVE_ORDER_SUPPLY = 'SET_ACTIVE_ORDER_SUPPLY'
export const SET_ACTIVE_INVENT = 'SET_ACTIVE_INVENT'
export const SET_LIST_FIRM = 'SET_LIST_FIRM'
export const SET_LIST_SHOPS = 'SET_LIST_SHOPS'
export const SET_LIST_UNIT_DIMENSION = 'SET_LIST_UNIT_DIMENSION'
export const REFRESH_ORDER_SUPPLY_LIST = 'REFRESH_ORDER_SUPPLY_LIST'
export const SET_ACTIVE_LOYAL = 'SET_ACTIVE_LOYAL'
export const REFRESH_LOYAL_LIST = 'REFRESH_LOYAL_LIST'
export const REFRESH_RULE_LOYAL_LIST = 'REFRESH_RULE_LOYAL_LIST'
export const REFRESH_NUM_SET_LIST = 'REFRESH_NUM_SET_LIST'
export const SET_LIST_TEMPLATE_BODY = 'SET_LIST_TEMPLATE_BODY'
export const SET_LIST_TEMPLATE_RESULT = 'SET_LIST_TEMPLATE_RESULT'
export const SET_RULE_TEMPLATE_PARAM = 'SET_RULE_TEMPLATE_PARAM'
export const SET_TEMPLATE_BODY = 'SET_TEMPLATE_BODY'
export const SET_LIST_TYPE_VALUE = 'SET_LIST_TYPE_VALUE'
export const SET_LIST_DEALER = 'SET_LIST_DEALER'
export const SET_GROUP_WARES_LIST = 'SET_GROUP_WARES_LIST'
export const SET_LIST_TEMPLATE_CONDITION = 'SET_LIST_TEMPLATE_CONDITION'
export const SET_DISCOUNT_GROUP_LIST = 'SET_DISCOUNT_GROUP_LIST'
export const SET_TYPE_ORDER_LIST = 'SET_TYPE_ORDER_LIST'
export const SET_TYPE_USE_LIST = 'SET_TYPE_USE_LIST'
export const SET_GROUP_CLIENT_LIST = 'SET_GROUP_CLIENT_LIST'
export const SET_LIST_TYPE_DISCOUNT = 'SET_LIST_TYPE_DISCOUNT'
export const SET_MARKET_SCHEME_LIST = 'SET_MARKET_SCHEME_LIST'
export const SET_WARES_PROPERTY_LIST = 'SET_WARES_PROPERTY_LIST'
export const SET_ACCESS_EVENT_LIST = 'SET_ACCESS_EVENT_LIST'
export const SET_DYNAMIC_LISTS = 'SET_DYNAMIC_LISTS'
export const SET_CONDITION_LISTS = 'SET_CONDITION_LISTS'
export const SET_TEMPLATE_RULE_LIST = 'SET_TEMPLATE_RULE_LIST'
//Banners feature!!!

// Banner Action Types
export const SET_BANNERS = 'SET_BANNERS';
export const SET_BANNER = 'SET_BANNER';
export const CLEAR_BANNER = 'CLEAR_BANNER';


//GroupBanner Action Types
export const SET_GROUP_BANNERS = 'SET_GROUP_BANNERS';
export const SET_GROUP_BANNER = 'SET_GROUP_BANNER';

//TypeBanner Action Types
export const SET_TYPE_BANNERS = 'SET_TYPE_BANNERS';

//Client Action Types
export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_CLIENT_BY_PHONE = 'SET_CLIENT_BY_PHONE';
export const SET_CLIENTS_BY_BARCODES = 'SET_CLIENTS_BY_BARCODE';
export const SET_CLIENT = 'SET_CLIENT';
export const CLEAR_CLIENTS = 'CLEAR_CLIENTS';

//GroupClient Action Types
export const SET_GROUP_CLIENTS = 'SET_GROUP_CLIENTS';
export const SET_GROUP_CLIENT = 'SET_GROUP_CLIENT';

//Designation Action Types
export const SET_STATUSES = 'SET_STATUSES';
export const SET_CHANNELS = 'SET_CHANNELS';