export const setActiveWindow = (actionType,windowType) => ({type: actionType, windowType: windowType  })
export const refreshInvoiceList = (actionType, dateRefreshInvoiceList) => ({type: actionType, dateRefreshInvoiceList: dateRefreshInvoiceList})
export const refreshWaresInvoiceList = (actionType, dateRefreshWaresInvoiceList) => ({type: actionType, dateRefreshWaresInvoiceList: dateRefreshWaresInvoiceList})
export const refreshEditForm = (actionType, dateRefreshEditInvoiceForm) => ({type: actionType, dateRefreshEditInvoiceForm: dateRefreshEditInvoiceForm})
export const setActiveInvoice = (actionType, invoice) => ({type: actionType, invoice: invoice})
export const setListFirm = (actionType, listFirm) => ({type: actionType, listFirm: listFirm})
export const setListShops = (actionType, listShops) => ({type: actionType, listShops: listShops})
export const setListUnitDimension = (actionType, listUnitDimension) => ({type: actionType, listUnitDimension: listUnitDimension})
export const refreshTransferInvoiceList = (actionType, dateRefreshTransferInvoiceList) => ({type: actionType, dateRefreshTransferInvoiceList: dateRefreshTransferInvoiceList})
export const setActiveTransferInvoice = (actionType, transferInvoice) => ({type: actionType, transferInvoice: transferInvoice})
export const refreshWaresTransferInvoiceList = (actionType, dateRefreshWaresTransferInvoiceList) => ({type: actionType, dateRefreshWaresTransferInvoiceList: dateRefreshWaresTransferInvoiceList})
export const refreshInventList = (actionType, dateRefreshInventList) => ({type: actionType, dateRefreshInventList: dateRefreshInventList})
export const refreshWaresInventList = ( actionType, dateRefreshWaresInventList) => ({type: actionType, dateRefreshWaresInventList: dateRefreshWaresInventList})
export const setActiveInvent = (actionType, invent) => ({type: actionType, invent: invent})
export const setActiveOrderSupply = (actionType, orderSupply) => ({type: actionType, orderSupply: orderSupply})
export const refreshOrderSupplyList = (actionType, dateRefreshOrderSupplyList) => ({type: actionType, dateRefreshOrderSupplyList: dateRefreshOrderSupplyList})
export const setActiveLoyal = (actionType, loyal) => ({type: actionType, loyal: loyal})
export const refreshLoyalList = (actionType, dateRefreshLoyalList) => ({type: actionType, dateRefreshLoyalList: dateRefreshLoyalList})
export const refreshRuleLoyalList = (actionType, dateRefreshRuleLoyalList) => ({type: actionType, dateRefreshRuleLoyalList: dateRefreshRuleLoyalList})
export const refreshNumSetList = (actionType, dateRefreshNumSetList) => ({type: actionType, dateRefreshNumSetList: dateRefreshNumSetList})
export const setListTemplateBody = (actionType, listTemplateBody) => ({type: actionType, listTemplateBody: listTemplateBody})
export const setListTemplateResult = (actionType, listTemplateResult) => ({type: actionType, listTemplateResult: listTemplateResult})
export const setListTemplateCondition = (actionType, listTemplateCondition) => ({type: actionType, listTemplateCondition: listTemplateCondition})
export const setRuleTemplateParam = (actionType, ruleTemplateParam) => ({type: actionType, ruleTemplateParam: ruleTemplateParam})
export const setTemplateBody = (actionType, templateBody) => ({type: actionType, templateBody: templateBody})
export const setListTypeValue = (actionType, listTypeValue) => ({type: actionType, listTypeValue: listTypeValue})
export const setListDealer = (actionType, listDealer) => ({type: actionType, listDealer: listDealer})
export const setGroupWaresList = (actionType, groupWaresList) => ({type: actionType, groupWaresList: groupWaresList})
export const setTypeOrderList = (actionType, typeOrderList) => ({type: actionType, typeOrderList: typeOrderList})
export const setTypeUseList = (actionType, typeUseList) => ({type: actionType, typeUseList: typeUseList})
export const setGroupClientList = (actionType, groupClientList) => ({type: actionType, groupClientList: groupClientList})
export const setTypeDiscountList = (actionType, typeDiscountList) => ({type: actionType, typeDiscountList: typeDiscountList})
export const setMarketSchemeList = (actionType, marketSchemeList) => ({type: actionType, marketSchemeList: marketSchemeList})
export const setWaresPropertyList = (actionType, waresPropertyList) => ({type: actionType, waresPropertyList: waresPropertyList})
export const setAccessEventList = (actionType, accessEventList) => ({type: actionType, accessEventList: accessEventList})


